/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.23.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.jio.tmf622.api;

import com.jio.tmf622.model.CancelProductOrder;
import com.jio.tmf622.model.CancelProductOrderCreate;
import com.jio.tmf622.model.Error;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-06-17T14:19:02.575985+05:30[Asia/Kolkata]", comments = "Generator version: 7.23.0")
@Validated
@Tag(name = "cancelProductOrder", description = "the cancelProductOrder API")
public interface CancelProductOrderApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_CANCEL_PRODUCT_ORDER = "/cancelProductOrder";
    /**
     * POST /cancelProductOrder : Creates a CancelProductOrder
     * This operation creates a CancelProductOrder entity.
     *
     * @param cancelProductOrder The CancelProductOrder to be created (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createCancelProductOrder",
        summary = "Creates a CancelProductOrder",
        description = "This operation creates a CancelProductOrder entity.",
        tags = { "cancelProductOrder" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = CancelProductOrder.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CancelProductOrderApi.PATH_CREATE_CANCEL_PRODUCT_ORDER,
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<CancelProductOrder> createCancelProductOrder(
        @Parameter(name = "cancelProductOrder", description = "The CancelProductOrder to be created", required = true) @Valid @RequestBody CancelProductOrderCreate cancelProductOrder
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"id\" : \"id\", \"href\" : \"href\", \"cancellationReason\" : \"cancellationReason\", \"effectiveCancellationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"requestedCancellationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"productOrder\" : { \"id\" : \"id\", \"href\" : \"href\", \"name\" : \"name\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\", \"@referredType\" : \"@referredType\" }, \"state\" : \"acknowledged\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LIST_CANCEL_PRODUCT_ORDER = "/cancelProductOrder";
    /**
     * GET /cancelProductOrder : List or find CancelProductOrder objects
     * This operation list or find CancelProductOrder entities
     *
     * @param fields Comma-separated properties to be provided in response (optional)
     * @param offset Requested index for start of resources to be provided in response (optional)
     * @param limit Requested number of resources to be provided in response (optional)
     * @return Success (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listCancelProductOrder",
        summary = "List or find CancelProductOrder objects",
        description = "This operation list or find CancelProductOrder entities",
        tags = { "cancelProductOrder" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json;charset=utf-8", array = @ArraySchema(schema = @Schema(implementation = CancelProductOrder.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CancelProductOrderApi.PATH_LIST_CANCEL_PRODUCT_ORDER,
        produces = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<List<CancelProductOrder>> listCancelProductOrder(
        @Parameter(name = "fields", description = "Comma-separated properties to be provided in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fields", required = false) @Nullable String fields,
        @Parameter(name = "offset", description = "Requested index for start of resources to be provided in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = false) @Nullable Integer offset,
        @Parameter(name = "limit", description = "Requested number of resources to be provided in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false) @Nullable Integer limit
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "[ { \"id\" : \"id\", \"href\" : \"href\", \"cancellationReason\" : \"cancellationReason\", \"effectiveCancellationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"requestedCancellationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"productOrder\" : { \"id\" : \"id\", \"href\" : \"href\", \"name\" : \"name\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\", \"@referredType\" : \"@referredType\" }, \"state\" : \"acknowledged\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }, { \"id\" : \"id\", \"href\" : \"href\", \"cancellationReason\" : \"cancellationReason\", \"effectiveCancellationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"requestedCancellationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"productOrder\" : { \"id\" : \"id\", \"href\" : \"href\", \"name\" : \"name\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\", \"@referredType\" : \"@referredType\" }, \"state\" : \"acknowledged\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_CANCEL_PRODUCT_ORDER = "/cancelProductOrder/{id}";
    /**
     * GET /cancelProductOrder/{id} : Retrieves a CancelProductOrder by ID
     * This operation retrieves a CancelProductOrder entity. Attribute selection is enabled for all first level attributes.
     *
     * @param id Identifier of the CancelProductOrder (required)
     * @param fields Comma-separated properties to provide in response (optional)
     * @return Success (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "retrieveCancelProductOrder",
        summary = "Retrieves a CancelProductOrder by ID",
        description = "This operation retrieves a CancelProductOrder entity. Attribute selection is enabled for all first level attributes.",
        tags = { "cancelProductOrder" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = CancelProductOrder.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CancelProductOrderApi.PATH_RETRIEVE_CANCEL_PRODUCT_ORDER,
        produces = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<CancelProductOrder> retrieveCancelProductOrder(
        @Parameter(name = "id", description = "Identifier of the CancelProductOrder", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "fields", description = "Comma-separated properties to provide in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fields", required = false) @Nullable String fields
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"id\" : \"id\", \"href\" : \"href\", \"cancellationReason\" : \"cancellationReason\", \"effectiveCancellationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"requestedCancellationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"productOrder\" : { \"id\" : \"id\", \"href\" : \"href\", \"name\" : \"name\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\", \"@referredType\" : \"@referredType\" }, \"state\" : \"acknowledged\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
