/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.23.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.jio.tmf622.api;

import com.jio.tmf622.model.CancelProductOrderCreateEvent;
import com.jio.tmf622.model.CancelProductOrderInformationRequiredEvent;
import com.jio.tmf622.model.CancelProductOrderStateChangeEvent;
import com.jio.tmf622.model.Error;
import com.jio.tmf622.model.EventSubscription;
import com.jio.tmf622.model.ProductOrderAttributeValueChangeEvent;
import com.jio.tmf622.model.ProductOrderCreateEvent;
import com.jio.tmf622.model.ProductOrderDeleteEvent;
import com.jio.tmf622.model.ProductOrderInformationRequiredEvent;
import com.jio.tmf622.model.ProductOrderStateChangeEvent;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-06-17T14:19:02.575985+05:30[Asia/Kolkata]", comments = "Generator version: 7.23.0")
@Validated
@Tag(name = "notification listeners (client side)", description = "the notification listeners (client side) API")
public interface ListenerApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_LISTEN_TO_CANCEL_PRODUCT_ORDER_CREATE_EVENT = "/listener/cancelProductOrderCreateEvent";
    /**
     * POST /listener/cancelProductOrderCreateEvent : Client listener for entity CancelProductOrderCreateEvent
     * Example of a client listener for receiving the notification CancelProductOrderCreateEvent
     *
     * @param data The event data (required)
     * @return Notified (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listenToCancelProductOrderCreateEvent",
        summary = "Client listener for entity CancelProductOrderCreateEvent",
        description = "Example of a client listener for receiving the notification CancelProductOrderCreateEvent",
        tags = { "notification listeners (client side)" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Notified", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = EventSubscription.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_LISTEN_TO_CANCEL_PRODUCT_ORDER_CREATE_EVENT,
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<EventSubscription> listenToCancelProductOrderCreateEvent(
        @Parameter(name = "data", description = "The event data", required = true) @Valid @RequestBody CancelProductOrderCreateEvent data
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"id\" : \"id\", \"callback\" : \"callback\", \"query\" : \"query\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LISTEN_TO_CANCEL_PRODUCT_ORDER_INFORMATION_REQUIRED_EVENT = "/listener/cancelProductOrderInformationRequiredEvent";
    /**
     * POST /listener/cancelProductOrderInformationRequiredEvent : Client listener for entity CancelProductOrderInformationRequiredEvent
     * Example of a client listener for receiving the notification CancelProductOrderInformationRequiredEvent
     *
     * @param data The event data (required)
     * @return Notified (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listenToCancelProductOrderInformationRequiredEvent",
        summary = "Client listener for entity CancelProductOrderInformationRequiredEvent",
        description = "Example of a client listener for receiving the notification CancelProductOrderInformationRequiredEvent",
        tags = { "notification listeners (client side)" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Notified", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = EventSubscription.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_LISTEN_TO_CANCEL_PRODUCT_ORDER_INFORMATION_REQUIRED_EVENT,
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<EventSubscription> listenToCancelProductOrderInformationRequiredEvent(
        @Parameter(name = "data", description = "The event data", required = true) @Valid @RequestBody CancelProductOrderInformationRequiredEvent data
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"id\" : \"id\", \"callback\" : \"callback\", \"query\" : \"query\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LISTEN_TO_CANCEL_PRODUCT_ORDER_STATE_CHANGE_EVENT = "/listener/cancelProductOrderStateChangeEvent";
    /**
     * POST /listener/cancelProductOrderStateChangeEvent : Client listener for entity CancelProductOrderStateChangeEvent
     * Example of a client listener for receiving the notification CancelProductOrderStateChangeEvent
     *
     * @param data The event data (required)
     * @return Notified (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listenToCancelProductOrderStateChangeEvent",
        summary = "Client listener for entity CancelProductOrderStateChangeEvent",
        description = "Example of a client listener for receiving the notification CancelProductOrderStateChangeEvent",
        tags = { "notification listeners (client side)" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Notified", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = EventSubscription.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_LISTEN_TO_CANCEL_PRODUCT_ORDER_STATE_CHANGE_EVENT,
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<EventSubscription> listenToCancelProductOrderStateChangeEvent(
        @Parameter(name = "data", description = "The event data", required = true) @Valid @RequestBody CancelProductOrderStateChangeEvent data
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"id\" : \"id\", \"callback\" : \"callback\", \"query\" : \"query\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LISTEN_TO_PRODUCT_ORDER_ATTRIBUTE_VALUE_CHANGE_EVENT = "/listener/productOrderAttributeValueChangeEvent";
    /**
     * POST /listener/productOrderAttributeValueChangeEvent : Client listener for entity ProductOrderAttributeValueChangeEvent
     * Example of a client listener for receiving the notification ProductOrderAttributeValueChangeEvent
     *
     * @param data The event data (required)
     * @return Notified (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listenToProductOrderAttributeValueChangeEvent",
        summary = "Client listener for entity ProductOrderAttributeValueChangeEvent",
        description = "Example of a client listener for receiving the notification ProductOrderAttributeValueChangeEvent",
        tags = { "notification listeners (client side)" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Notified", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = EventSubscription.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_LISTEN_TO_PRODUCT_ORDER_ATTRIBUTE_VALUE_CHANGE_EVENT,
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<EventSubscription> listenToProductOrderAttributeValueChangeEvent(
        @Parameter(name = "data", description = "The event data", required = true) @Valid @RequestBody ProductOrderAttributeValueChangeEvent data
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"id\" : \"id\", \"callback\" : \"callback\", \"query\" : \"query\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LISTEN_TO_PRODUCT_ORDER_CREATE_EVENT = "/listener/productOrderCreateEvent";
    /**
     * POST /listener/productOrderCreateEvent : Client listener for entity ProductOrderCreateEvent
     * Example of a client listener for receiving the notification ProductOrderCreateEvent
     *
     * @param data The event data (required)
     * @return Notified (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listenToProductOrderCreateEvent",
        summary = "Client listener for entity ProductOrderCreateEvent",
        description = "Example of a client listener for receiving the notification ProductOrderCreateEvent",
        tags = { "notification listeners (client side)" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Notified", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = EventSubscription.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_LISTEN_TO_PRODUCT_ORDER_CREATE_EVENT,
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<EventSubscription> listenToProductOrderCreateEvent(
        @Parameter(name = "data", description = "The event data", required = true) @Valid @RequestBody ProductOrderCreateEvent data
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"id\" : \"id\", \"callback\" : \"callback\", \"query\" : \"query\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LISTEN_TO_PRODUCT_ORDER_DELETE_EVENT = "/listener/productOrderDeleteEvent";
    /**
     * POST /listener/productOrderDeleteEvent : Client listener for entity ProductOrderDeleteEvent
     * Example of a client listener for receiving the notification ProductOrderDeleteEvent
     *
     * @param data The event data (required)
     * @return Notified (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listenToProductOrderDeleteEvent",
        summary = "Client listener for entity ProductOrderDeleteEvent",
        description = "Example of a client listener for receiving the notification ProductOrderDeleteEvent",
        tags = { "notification listeners (client side)" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Notified", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = EventSubscription.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_LISTEN_TO_PRODUCT_ORDER_DELETE_EVENT,
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<EventSubscription> listenToProductOrderDeleteEvent(
        @Parameter(name = "data", description = "The event data", required = true) @Valid @RequestBody ProductOrderDeleteEvent data
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"id\" : \"id\", \"callback\" : \"callback\", \"query\" : \"query\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LISTEN_TO_PRODUCT_ORDER_INFORMATION_REQUIRED_EVENT = "/listener/productOrderInformationRequiredEvent";
    /**
     * POST /listener/productOrderInformationRequiredEvent : Client listener for entity ProductOrderInformationRequiredEvent
     * Example of a client listener for receiving the notification ProductOrderInformationRequiredEvent
     *
     * @param data The event data (required)
     * @return Notified (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listenToProductOrderInformationRequiredEvent",
        summary = "Client listener for entity ProductOrderInformationRequiredEvent",
        description = "Example of a client listener for receiving the notification ProductOrderInformationRequiredEvent",
        tags = { "notification listeners (client side)" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Notified", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = EventSubscription.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_LISTEN_TO_PRODUCT_ORDER_INFORMATION_REQUIRED_EVENT,
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<EventSubscription> listenToProductOrderInformationRequiredEvent(
        @Parameter(name = "data", description = "The event data", required = true) @Valid @RequestBody ProductOrderInformationRequiredEvent data
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"id\" : \"id\", \"callback\" : \"callback\", \"query\" : \"query\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LISTEN_TO_PRODUCT_ORDER_STATE_CHANGE_EVENT = "/listener/productOrderStateChangeEvent";
    /**
     * POST /listener/productOrderStateChangeEvent : Client listener for entity ProductOrderStateChangeEvent
     * Example of a client listener for receiving the notification ProductOrderStateChangeEvent
     *
     * @param data The event data (required)
     * @return Notified (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listenToProductOrderStateChangeEvent",
        summary = "Client listener for entity ProductOrderStateChangeEvent",
        description = "Example of a client listener for receiving the notification ProductOrderStateChangeEvent",
        tags = { "notification listeners (client side)" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Notified", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = EventSubscription.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_LISTEN_TO_PRODUCT_ORDER_STATE_CHANGE_EVENT,
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    default ResponseEntity<EventSubscription> listenToProductOrderStateChangeEvent(
        @Parameter(name = "data", description = "The event data", required = true) @Valid @RequestBody ProductOrderStateChangeEvent data
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"id\" : \"id\", \"callback\" : \"callback\", \"query\" : \"query\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"code\" : \"code\", \"reason\" : \"reason\", \"message\" : \"message\", \"status\" : \"status\", \"referenceError\" : \"https://openapi-generator.tech\", \"@baseType\" : \"@baseType\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"@type\" : \"@type\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
